name: 'Reset component-updates branch'

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  resetBranch:
    name: 'Reset component-updates branch'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 'Checkout component-updates'
        run: |
          git checkout -b component-updates

      - name: 'Reset branch'
        run: |
          git reset --hard origin/main
      
      - name: 'Push'
        run: |
          git push --set-upstream origin component-updates --force